export const SET_TOKEN = 'SET_TOKEN';
export const SET_PARTICIPANTS = 'SET_PARTICIPANTS';
export const SET_WAIT_PARTICIPANTS = 'SET_WAIT_PARTICIPANTS';
export const SET_ACTIVE_PARTICIPANTS = 'SET_ACTIVE_PARTICIPANTS';
export const SET_RISE_PARTICIPANT = 'SET_RISE_PARTICIPANT';
