export const GET_UNIVERSITIES = 'GET_ALL_UNIVERSITIES';
export const SET_BOOK_INFO = 'SET_BOOK_INFO';
export const SET_USER_ACCOUNT = 'SET_USER_ACCOUNT';
export const SET_PREMIUM_PLAN = 'SET_PREMIUM_PLAN';
